=== Tishar07/MangaWeb/XSD/manga.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="MangaList">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Manga" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="MangaID" type="xs:int"/>
                            <xs:element name="MangaName" type="xs:string"/>
                            <xs:element name="FrontCover" type="xs:string"/>
                            <xs:element name="MangaDescription" type="xs:string"/>
                            <xs:element name="Price" type="xs:decimal"/>

                            <xs:element name="Genres">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Genre" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Tishar07/MangaWeb/XSD/mangalistdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<MangaList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="manga.xsd">

    <Manga>
        <MangaID></MangaID>
        <MangaName></MangaName>
        <FrontCover></FrontCover>
        <MangaDescription></MangaDescription>
        <Price></Price>

        <Genres>
            <Genre></Genre>
        </Genres>
    </Manga>

</MangaList>
